# .github/workflows/deploy.yml
name: Deploy with Zero Downtime & Rollback

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: application.properties 생성
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: 실행권한 부여
        run: chmod +x ./gradlew

      - name: 빌드
        run: ./gradlew clean build -x test

      - name: 빌드 후 파일 확인
        run: ls -al ./build/libs

      - name: 빌드 후 루트 디렉토리 확인
        run: ls -al .


      - name: JAR 파일 이름 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./s3board.jar

      - name: SCP로 파일 전송 (JAR + deploy.sh)
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: s3board.jar
          target: /home/ubuntu/s3board/targetdir

      - name: SSH로 배포 스크립트 실행
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # chmod +x /home/ubuntu/s3board/targetdir/deploy.sh
            # /home/ubuntu/s3board/targetdir/deploy.sh
            
